name: build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Check the package and run the tests
      env:
        DATAHUB_APIKEY: ${{ secrets.DATAHUB_APIKEY }}
      run: make check && make test
